spring.application.name=client
# Para um MongoDB local (se voc\u00EA o tiver instalado), a URL seria:
spring.data.mongodb.uri=mongodb+srv://rapha_user:Lore123@project.krqf2qy.mongodb.net/clientes?retryWrites=true&w=majority&appName=Project
logging.level.com.basic=DEBUG
