spring.application.name=client
# A URL do MongoDB ser\u00E1 lida da vari\u00E1vel de ambiente 'MONGO_URI'.
# Se a vari\u00E1vel n\u00E3o existir, a aplica\u00E7\u00E3o usar\u00E1 a URL local padr\u00E3o.
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/clientes}
logging.level.com.basic=DEBUG